$(function(){
   $('#header_icone').click(function(e){
       e.preventDefault();
       $('body').toggleClass('with_sidebar');
   });
    $('#site-cache').click(function(e){
        $('body').removeClass('with_sidebar');
    })
})